name: HTML Check

on:
  push:


jobs:
  check-with-w3c:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Wait for github pages deployment
        run: |
          echo "Waiting 70s for github pages deployment"
          sleep 70
        
      
      - name: Call W3C API
        run: |
          chmod +x ${GITHUB_WORKSPACE}/.github/scripts/W3CApi.sh  # Make the script executable
          bash ${GITHUB_WORKSPACE}/.github/scripts/W3CApi.sh
          if [ $? -eq 1 ]; then
            echo $(curl -s "https://validator.nu/?doc=https://johan-uqac.github.io/CV&out=gnu")
            exit 1
          fi