name: HTML Check

on:
  push:


jobs:
  check-with-w3c:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Wait for github pages deployment
        run: |
          echo "Waiting 70s for github pages deployment"
          sleep 70
        
      
      - name: Call W3C API
        run: |
          line_length=$(echo $(curl -s "https://validator.nu/?doc=https://johan-uqac.github.io/CV&out=gnu") | wc -m | tail -n 1 | tr -d ' ')

          if [ $line_length != 1 ]; then
              curl -s "https://validator.nu/?doc=https://johan-uqac.github.io/CV&out=gnu" > ${GITHUB_WORKSPACE}/errors.txt
              echo "W3C_ERRORS=1" >> $GITHUB_ENV
          else
              echo "W3C_ERRORS=0" >> $GITHUB_ENV
          fi
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: errors
          path: ${GITHUB_WORKSPACE}/errors.txt
        if: env.W3C_ERRORS == '1'
      
      - name: Exit if there is an error
        run: |
          if [ $W3C_ERRORS -eq 1 ]; then
            exit 1
          fi