name: HTML Check

on:
  push:


jobs:
  run-html5validator:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checks HTML5
      uses: Cyb3r-Jak3/html5validator-action@v7.2.0
      with:
        root: ./
        css: true
        format: json
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: log
        path: log.log
